# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Danielle Lamb, Graphic Designer, Cambridgeshire, Leicestershire and Lincolnshire
email: danielle.lamb@icloud.com
description: I am a multidisciplinary designer focusing on print, art direction, infographics and branding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daniellelamb.co.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
